version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5150:5150"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules  
    command: sh -c "npx knex migrate:latest && npm start"
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  
    volumes:
      - ./frontend:/app
      - /app/node_modules 
